# Generated by Django 5.0.2 on 2024-09-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAs', models.CharField(max_length=50, verbose_name='Nombre de la Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCareer', models.CharField(max_length=50, verbose_name='Nombre de la Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCourse', models.CharField(max_length=25, verbose_name='Nombre del Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Imagen'), ('reading', 'Lectura')], max_length=10, verbose_name='Tipo de Material')),
                ('content', models.TextField(verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRol', models.CharField(max_length=20, verbose_name='Nombre del Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('options', models.TextField(verbose_name='Opciones')),
                ('correctOption', models.TextField(verbose_name='Opción Correcta')),
                ('asignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.asignature', verbose_name='Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.material', verbose_name='Material')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('testDate', models.DateField(verbose_name='Fecha de la Prueba')),
                ('testTime', models.TimeField(verbose_name='Hora de la Prueba')),
                ('numQuestions', models.IntegerField(verbose_name='Número de Preguntas')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course', verbose_name='Curso')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Puntaje')),
                ('answers', models.TextField(verbose_name='Respuestas')),
                ('passed', models.BooleanField(verbose_name='Aprobado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test', verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='Pregunta')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.test', verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('namUsu', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
                ('lasUsu', models.CharField(max_length=50, verbose_name='Apellido del Usuario')),
                ('typeDoc', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('CC', 'Cédula de Ciudadanía')], max_length=2, verbose_name='Tipo de Documento')),
                ('numDoc', models.CharField(max_length=12, verbose_name='Número de Documento')),
                ('email', models.EmailField(max_length=125, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=8, verbose_name='Contraseña')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.role', verbose_name='Rol')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='userProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.user', verbose_name='Profesor'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.career', verbose_name='Carrera')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.user', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('asignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.asignature', verbose_name='Asignatura')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.user', verbose_name='Profesor')),
            ],
        ),
    ]
