# Generated by Django 5.0.2 on 2024-10-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_test_duration_test_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_time',
        ),
    ]
