# Generated by Django 5.0.2 on 2024-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_test_duration_remove_test_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timeDu',
            field=models.IntegerField(default=60, verbose_name='Duración de la Prueba'),
        ),
    ]
