# Generated by Django 5.0.2 on 2024-10-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_test_timedu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='userProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.user', verbose_name='PROFESOR'),
        ),
    ]
