# Generated by Django 5.0.2 on 2024-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_test_userprofesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='testTime',
        ),
        migrations.RemoveField(
            model_name='test',
            name='timeDu',
        ),
        migrations.AddField(
            model_name='test',
            name='tesTimF',
            field=models.TimeField(null=True, verbose_name='Hora de la Prueba Fin'),
        ),
        migrations.AddField(
            model_name='test',
            name='tesTimI',
            field=models.TimeField(null=True, verbose_name='Hora de la Prueba Inicio'),
        ),
        migrations.AddField(
            model_name='test',
            name='timeDuration',
            field=models.IntegerField(default=0, verbose_name='Duración de la Prueba'),
        ),
    ]
