# Generated by Django 5.0.2 on 2024-10-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_test_testtime_remove_test_timedu_test_testimf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Attempts',
            field=models.IntegerField(default=1, verbose_name='Intentos'),
        ),
        migrations.AddField(
            model_name='test',
            name='typeExa',
            field=models.CharField(choices=[('PT', 'Practica'), ('EM', 'Modulo'), ('ED', 'Diagnostico')], default='PT', max_length=2, verbose_name='Tipo de Prueba'),
        ),
        migrations.AlterField(
            model_name='test',
            name='userProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.user', verbose_name='Profesor encargado'),
        ),
    ]
