# Generated by Django 5.0.2 on 2024-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_test_attempts_test_typeexa_alter_test_userprofesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='typeExa',
            field=models.CharField(choices=[('PT', 'Práctica'), ('EM', 'Módulo'), ('ED', 'Diagnóstico')], default='PT', max_length=2, verbose_name='Tipo de Prueba'),
        ),
    ]
