# Generated by Django 5.0.2 on 2024-10-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_test_typeexa'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='moduEx',
            field=models.TextField(null=True, verbose_name='Modulo Examen'),
        ),
    ]
