# Generated by Django 5.0.2 on 2024-10-17 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='fecha',
            new_name='datef',
        ),
    ]
