# Generated by Django 5.0.2 on 2024-10-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_rename_fecha_examresult_datef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='datef',
            new_name='dateF',
        ),
    ]
