# Generated by Django 5.0.2 on 2024-10-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_rename_datef_examresult_datef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='dateF',
            new_name='fecha',
        ),
    ]
