# Generated by Django 5.0.4 on 2024-10-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_examresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='Attempts',
            field=models.IntegerField(default=0, verbose_name='Intentos'),
        ),
    ]
