# Generated by Django 5.1.2 on 2024-10-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_course_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='nomCourse',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre del Curso'),
        ),
    ]
